site_name: HEO
site_url: https://heo.fi/

nav: 

    - Project case study: 
        - Project context.: index.md
        - Project overview.: project_overview.md
    - Problem formulating: 
        - Variables.: lp_vars.md
        - Parameters.: parameters.md
        - Upper and lower bounds.: low_up_bnds.md
        - Problem constraints.: lp_cstrs.md
        - Objective.: obj_func.md
        - Problem size.: prblm_size.md
    - Implementation: 
        - User quick guide.: user_quick_guide.md
        - Contributor guide.: contr_guide.md
    - About: 
        - Authors.: authors.md
        - Releases.: chng_log.md




markdown_extensions:
    - toc:
        permalink: true 
    - pymdownx.arithmatex:
        generic: true 
    - attr_list
    - pymdownx.snippets:
        check_paths: false
        url_timeout: 15.0
        encoding: 'utf-8'
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
        alt: short
        options:
            attributes:
                align: absmiddle
                height: 20px
                width: 20px

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme: readthedocs

