site_name: HYH
site_url: https://hyh.fi/

nav: 
    - Getting started.: index.md
    - Project context.: Project description and context.md
    - Project study case: 
        - Overview: Project_study_case.md

markdown_extensions:
    - toc:
        permalink: true  


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme: readthedocs


