site_name: HEO
site_url: https://heo.fi/

nav: 

    - Project case study.: 
        - Project context.: Project description and context.md
        - Project overview.: Project_overview.md
    - Getting started.: index.md
    - Problem formulating.: 
        - Problem Parameters.: parameters.md
        - Problem LP variables.: lp_vars.md
        - Problem LP constraints.: lp_cstrs.md
        - Optimization objective.: obj_func.md
    - Implementation.: 
        - User quick guide.: user_quick_guide.md
        - Contributor guide.: contr_guide.md
    - About.: 
        - Authors.: authors.md
        - Changelog & Versionning.: chng_log.md


markdown_extensions:
    - toc:
        permalink: true  


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme: readthedocs

